replicaCount: 1

image:
  name: voonya/root-service
  containerName: root-service
  port: 8080
  tag: latest

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/root-service
  port: http
