apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: file-service-virtual
spec:
  hosts:
    - file-manager-service
  http:
    - route:
        - destination:
            host: file
      timeout: 5s
