apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: file-service-circuit-breaker
spec:
  host: file-manager-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80
