apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-db
  template:
    metadata:
      labels:
        app: auth-service-db
    spec:
      containers:
        - name: auth-service-db
          image: postgres:14.1-alpine3.15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-service-db-config
            - secretRef:
                name: auth-service-db-secret
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: auth-service-db-claim
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    app: postgres-db
spec:
  ports:
    - port: 5432
  selector:
    app: auth-service-db