apiVersion: batch/v1
kind: Job
metadata:
  name: migration-auth-db
spec:
  template:
    spec:
      containers:
        - name: migration-auth-db
          image: voonya/migration-auth-db
          imagePullPolicy: Never
          command: [ './MigrationsApplier' ]
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
          env:
            - name: DB_URL
              value: "Host=$(DB_HOST); Port=$(DB_PORT); Database=$(DB_NAME); User Id=$(DB_USERNAME); Password=$(DB_PASSWORD)"
      restartPolicy: Never
  backoffLimit: 4