replicaCount: 1

selector:
  app: file-service

image:
  name: voonya/file-service
  containerName: file-service
  port: 8080

migrations:
  image: voonya/migration-files-db
  name: migration-files-db
  backoffLimit: 4

service:
  containerPort: 8080
  port: 80

volume:
  storage:
    name: file-storage
    claimName: file-storage
    mountPath: /usr/share/file-storage/files

ingress:
  path: /api/file-service
  port: 80
  proxyBodySize: 512m

configs:
  PORT: 8080
  DB_DIALECT: postgres
  FILEPATH: share/file-storage/files
  DB_HOST: files-db
  DB_PORT: 5432

secrets:
  DB_NAME: ZmlsZXNEQg==
  DB_USERNAME: ZmlsZXNEQg==
  DB_PASSWORD: cGFzc3dvcmQ=
