replicaCount: 1

selector:
  app: file-service

image:
  name: voonya/file-service
  port: 8080

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

volume:
  storage:
    name: file-storage
    claimName: file-storage
    mountPath: /usr/share/file-storage/files

ingress:
  path: /api/service1
  port: http
  proxyBodySize: 512m

configs:
  PORT: 8080
  DB_DIALECT: postgres
  FILEPATH: share/file-storage/files
  DB_HOST: files-db
  DB_PORT: 5432

secrets:
  DB_NAME: ZmlsZXNEQg==
  DB_USERNAME: ZmlsZXNEQg==
  DB_PASSWORD: cGFzc3dvcmQ=
