version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - 8080:8080
    volumes:
      - file-storage:/usr/node/app
volumes:
  file-storage:
    external: true