apiVersion: batch/v1
kind: Job
metadata:
  name: migration-files-db
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: migration-files-db
          image: voonya/migration-files-db
          imagePullPolicy: Always
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - configMapRef:
                name: file-service-config
            - secretRef:
                name: file-service-secret
          env:
            - name: DB_URL
              value: "$(DB_DIALECT)://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
      restartPolicy: Never
  backoffLimit: 4
