{{- define "common.deployment" -}}

{{- $common := dict "Values" .Values.common -}} # Values з common Chart
{{- $noCommon := omit .Values "common" -}} # Values з основного Chart
{{- $overrides := dict "Values" $noCommon -}} # записуємо common Values в змінну Values
{{- $noValues := omit . "Values" -}} # містить усе крім Values, зокрема Chart, Release
{{- with merge $noValues $overrides $common -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       {{- include "common.selectorLabels" . | nindent 8 }}              # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.image.containerName }}
          imagePullPolicy: Always
          {{- if .Values.volume }}
          volumeMounts:
            - mountPath: {{ .Values.volume.mountPath }}
              name: {{ .Values.volume.name }}
          {{- end }}
          ports:
          {{- range .Values.service.ports }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
          {{- end }}
          envFrom:
            - configMapRef:
                optional: true
                name: {{ include "common.fullname" $ }}-config
            - secretRef:
                optional: true
                name: {{ include "common.fullname" $ }}-secret
          env:
            - name: DB_URL
              value: "$(DB_DIALECT)://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
            - name: DB_URL_DOTNET
              value: "Host=$(DB_HOST); Port=$(DB_PORT); Database=$(DB_NAME); User Id=$(DB_USERNAME); Password=$(DB_PASSWORD)"
      {{- if .Values.volume }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claimName }}
      {{- end }}
{{- end -}}
{{- end -}}