{{- define "common.dotnetMigration" -}}

{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}-migration
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.migrations.name }}
          image: {{ .Values.migrations.image }}
          imagePullPolicy: Always
          command: [ './MigrationsApplier' ]
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" . }}-config
            - secretRef:
                name: {{ include "common.fullname" . }}-secret
          env:
            - name: DB_URL
              value: "Host=$(DB_HOST); Port=$(DB_PORT); Database=$(DB_NAME); User Id=$(DB_USERNAME); Password=$(DB_PASSWORD)"
      restartPolicy: Never
  backoffLimit: {{ .Values.migrations.backoffLimit }}
{{- end -}}
{{- end -}}
