replicaCount: 1

virtualservice:
  timeout: "5s"

image:
  name: voonya/profile
  containerName: profile
  port: 8080
  tag: latest

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

migrations:
  image: voonya/migration-profile-db
  name: migration-profile-db
  backoffLimit: 4

ingress:
  path: /api/profile
  port: http

configs:
  PORT: 8080
  DB_DIALECT: postgres
  DB_HOST: profile-db
  DB_PORT: 5432

secrets:
  DB_NAME: cHJvZmlsZXNEQg==
  DB_USERNAME: cHJvZmlsZXNEQg==
  DB_PASSWORD: cGFzc3dvcmQ=

postgresql:
  nameOverride: profile-db
  fullnameOverride: profile-db
  postgresqlDatabase: "profilesDB"
  postgresqlUsername: "profilesDB"
  postgresqlPassword: "password"
  postgresqlPostgresPassword: "password"
  persistence:
    size: 5Gi
    mountPath: /var/lib/postgresql/profilesdb/data
