apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Value.ingress.proxyBodySize }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Value.ingress.path }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Chart.Name }}
                port:
                  name: {{ .Values.ingress.port }}