apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.migrations.name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.migrations.name }}
          image: {{ .Values.migrations.image }}
          imagePullPolicy: Always
          command: [ 'npx', 'prisma', 'migrate', 'deploy' ]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
          env:
            - name: DB_URL
              value: "$(DB_DIALECT)://$(DB_NAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
      restartPolicy: Never
  backoffLimit: {{ .Values.migrations.backoffLimit }}