apiVersion: batch/v1
kind: Job
metadata:
  name: migration-schedule-db
spec:
  template:
    spec:
      containers:
        - name: migration-schedule-db
          image: voonya/migration-schedule-db
          imagePullPolicy: Always
          command: [ 'npx', 'prisma', 'migrate', 'deploy' ]
          envFrom:
            - configMapRef:
                name: schedule-service-config
            - secretRef:
                name: schedule-service-secret
          env:
            - name: DB_URL
              value: "$(DB_DIALECT)://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)"
      restartPolicy: Never
  backoffLimit: 4